### ISSUE TITLE
ModuleNotFoundError: No module named 'fastai.core'

### ISSUE THREAD

**Issue by marade** [ZhangDengwei/IIBacFinder#2]
$ python predict.py
Traceback (most recent call last):
  File "/home/ubuntu/IIBacFinder/scripts/predict.py", line 22, in <module>
    from leader_predict import leader
  File "/home/ubuntu/IIBacFinder/scripts/leader_predict.py", line 20, in <module>
    from protai.annotation.data import DatasetGenerator as ADG
  File "/home/ubuntu/IIBacFinder/scripts/cleavage_pred/protai/annotation/data.py", line 4, in <module>
    from fastai.core import PathOrStr
ModuleNotFoundError: No module named 'fastai.core'

**Comment by marade** [comment]
I was able to get this working using the very old, deprecated fastai1 files. It would be much better to use code that isn't so old and is supported.

**Comment by ZhangDengwei** [comment]
Thanks for your interest in IIBacFinder. I will release the wapper and more detailed document soon.

**Comment by marade** [comment]
Thanks!
